function Hd = filt_int5_cic
%FILT_INT5_CIC Returns a multirate filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 30-Jan-2025 11:06:09

intf    = 5;  % Interpolation Factor
diffd   = 1;  % Differential Delay
numsecs = 3;  % Number of Sections

Hd = dsp.CICInterpolator( ...
    'InterpolationFactor', intf, ...
    'DifferentialDelay', diffd, ...
    'NumSections', numsecs);

% [EOF]
