function Hd = int_x2
%INT_X2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 17-Jan-2025 10:04:33

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 24;  % Sampling Frequency

Fpass = 3;               % Passband Frequency
Fstop = 9;               % Stopband Frequency
Dpass = 0.011512416822;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = b; % dfilt.dffir(b);

% [EOF]
